api_keys:
  anthropic: "YOUR_ANTHROPIC_KEY" # replace YOUR_ANTHROPIC_KEY with your key
  roboflow: "YOUR_ROBOFLOW_KEY" # replace YOUR_ROBOFLOW_KEY with your key

processing:
  process_metadata: false  # Set true if FMNH-style metadata is present
  transcribe_barcodes: false  # Set to false if no unit tray-level barcodes
  transcribe_taxonomy: true  # Set to false if no unit tray-level taxonomic IDs
  transcribe_specimen_labels: false  # Set to false to skip specimen label transcription

roboflow:
  workspace: "field-museum" # FMNH workspace is default
  models:
    drawer:
      endpoint: "trayfinder-base" # obj detection, finds trays in drawers
      version: 2
      confidence: 50 # adjustable, set from 1-99 (higher # = greater threshold for predictions)
      overlap: 50 # adjustable, set from 1-99 (higher # = higher expected overlap between bounding boxes)
    tray:
      endpoint: "bugfinder-kdn9e" # obj detection, finds specimens in trays
      version: 13
      confidence: 50
      overlap: 50
    label:
      endpoint: "labelfinder" # obj detection, finds label parts
      version: 7
      confidence: 50
      overlap: 50
    mask:
      endpoint: "bugmasker-all"  # segmentation, outlines specimen bodies
      version: 2 
      confidence: 50
    pin:
      endpoint: "pinmasker" # segmentation, outlines pin
      version: 5
      confidence: 50

prompts:
  barcode: # prompt for transcribing barcodes
    system: |
      You are a barcode reading tool. You should output only the number 
      (or letter-number string) found in the image. If no valid barcode 
      is found, output 'none'.
    user: |
      Read the barcode number. Output only the code, no explanations.
  
  taxonomy: # prompt for transcribing and organizing taxonomic IDs
    system: |
      You are a taxonomic label transcription tool specializing in natural 
      history specimens. Your task is to:
      1. Provide a complete transcription of the entire label
      2. Extract the taxonomic name, including any genus, subgenus, species, 
         and subspecies information
      3. Extract the taxonomic authority (author and year)

      For missing elements, output 'none'. Format your response as a structured 
      dictionary with these three keys:
      {
        'full_transcription': 'complete text as shown',
        'taxonomy': 'only taxonomic name (Genus (Subgenus) species subspecies)', 
        'authority': 'author, year'
      }
    user: |
      Transcribe this taxonomic label, preserving the exact text and extracting 
      the taxonomic name and authority. Output only the dictionary, no explanations.
  
  specimen_label: # prompt for transcribing any visible text, verbatim, from specimen labels
    system: |
     You are a natural history specimen label transcription tool specializing in precise, verbatim transcription. Your task is to:
          1. Transcribe ALL visible text exactly as it appears, including:
             - Unclear, handwritten, or partially visible text
          2. Do not interpret, correct, or standardize any text
          3. Most text will be horizontal, read left-to-right. 
          4. Occasionally, text may be vertical or upside-down.
    user: |
      Transcribe any visible text. Output 'no text found' if none visible. 
      Transcribe text verbatim. No explanations, descriptions, or commentary.
  
  location: # prompt for estimating locations from verbatim text
    system: |
      You are a geographic data extractor specialized in natural history specimen labels. 
      Your task is to:
      1. Look for geographic information only, considering:
         - Country, state/province, county, city, specific locality
      2. IGNORE non-geographic elements:
         - Collection metadata (Det., Coll., FMNH, Field Museum, Museum)
         - Taxonomic information
         - Dates and collector names
      3. For geographic inference:
         - Only infer larger regions when unambiguous (e.g., "Paris, France" -> "France")
         - Do not infer if multiple possibilities exist (e.g., "Springfield" could be many states)
         - Include only explicitly stated or unambiguously implied locations
      4. Handle special cases:
         - Historical place names: use historical name, add modern name in brackets
    user: |
      Extract geographic location from this text: {text}. Format: largest to 
      smallest unit, comma-separated. Output 'no location found' if none present. 
      No explanations or notes.
  
  validation: # prompt for comparing/validating estimated locations to the verbatim text
    system: |
      You are a geographic data validator specializing in museum specimen labels. 
      Your task is to:
      1. Examine the transcribed text and interpreted location to evaluate whether they are a strong match
      2. Make a final location determination considering:
         - The verbatim transcribed text
         - The proposed location
         - Standard geographic abbreviations in specimen labels (e.g., USA: MT = USA, Montana)
         - Some partial information is still valid (e.g., a clear state/province even without city/county)
         - Conventional collection abbreviations, e.g. Det. / Col. are typically not locations
         - Locations derived from 'Field Museum' or 'FMNH' or 'Chicago Field Museum' 
           are not valid, as this is where many specimens are housed
         - Avoid specific directional information as this easy to misinterpret
           
      3. Respond with a dictionary containing these fields:
        {
          'verbatim_text': The raw text exactly as transcribed from the original image,
          'proposed_location': The location string being validated,
          'validation_status': Must be one of these exact values:
              'VERIFIED' - Use when:
                  - Text contains clear geographic identifiers (e.g., standard country/state codes like "USA: MT")
                  - Location matches established abbreviation conventions
                  - Partial location information is okay if unambiguous (e.g., clear state without county)
              'UNRELIABLE' - Use when:
                  - Geographic terms are ambiguous or could be non-geographic
                  - Location interpretation goes beyond what's supported by the text
                  - Proposed location misinterprets collection abbreviations (e.g., reading 'Det.' as Detroit)
              'UNKNOWN' - Use when no clear location information is found in the text,
          'final_location': Must be either:
              - A standardized location string from largest to smallest unit (e.g., "USA, Montana")
                which can be:
                * A new determination if the proposed location was incorrect
                * An expansion of a previous valid determination with newly validated details
                * A more conservative version of the proposed location if only part can be verified
                (only if status is VERIFIED)
              - 'UNKNOWN' (for UNRELIABLE or UNKNOWN status),
          'confidence_notes': A single concise sentence explaining the validation decision
        }
    user: |
      Validate this location data:
      Transcribed text: {transcribed_text}
      Proposed location: {proposed_location}

directories:
  fullsize: "drawers/fullsize"
  metadata: "drawers/fullsize/capture_metadata"
  resized: "drawers/resized"
  coordinates: "drawers/resized/coordinates"
  trays: "drawers/trays"
  guides: "drawers/guides"
  resized_trays: "drawers/resized_trays"
  resized_trays_coordinates: "drawers/resized_trays/coordinates"
  label_coordinates: "drawers/resized_trays/label_coordinates"
  labels: "drawers/labels"
  specimens: "drawers/specimens"
  mask_coordinates: "drawers/masks/mask_coordinates"
  mask_png: "drawers/masks/mask_png"
  measurements: "drawers/measurements"
  no_background: "drawers/masks/no_background"
  pin_coordinates: "drawers/masks/pin_coords"
  full_masks: "drawers/masks/full_masks"
  transparencies: "drawers/transparencies"
  whitebg_specimens: "drawers/whitebg_specimens"
  specimen_level: "drawers/transcriptions/specimen_labels"
  tray_level: "drawers/transcriptions/tray_labels"
  data: "drawers/data"

resources:
  # !! Did this part very on the fly... still need to integrate consistently among functions!!
  memory:
    sequential: false    # Process in parallel by default
    max_workers: null    # null = automatic based on CPU
    batch_size: null     # null = process all at once
    
    # Step-specific overrides (only for steps that need special handling)
    step_overrides:
      resize_drawers:    
        sequential: true # Process one image at a time
        batch_size: 1    # One image per batch
      crop_trays:    
        sequential: true # Process one image at a time
        batch_size: 1    # One image per batch
      outline_specimens:
        sequential: false
        max_workers: 40
      outline_pins:
        sequential: false
        max_workers: 40
      create_transparency:
        sequential: false
        max_workers: 40  
